"""Personalised film metadata and ratings for Cannes 2026.

Rating scale is calibrated to use the full 0-10 range:

TASTE (alignment with Daniel's Letterboxd):
  10  Peak match — bold/stylish/sensory/maximalist auteur (Refn, Harari body-swap,
      Mandico, Na Hong-jin genre, Dupieux absurd)
  9   Strong match — genre-forward, director already loved
  8   High match — well-reviewed auteur in Daniel's register
  7   Good match — competent auteur, likely 3.5-4 stars
  6   Mixed — could go either way, risk of drift
  5   Lukewarm — arthouse that may land like Close (3.5) or Sentimental Value (3.5)
  4   Low — quiet restrained arthouse (Berlin School, slow Latin American)
  3   Likely miss — aligns with 1-2 star ratings (Renoir, Saltburn, Lady Bird)
  2   Strong miss
  1   Almost certainly disliked

PRESTIGE (section + director stature):
  10  Palme winner returning (Almodóvar, Mungiu, Kore-eda, Farhadi, Hamaguchi)
  9   Major competition auteur (Pawlikowski, Gray, Nemes, Zvyagintsev, Dhont,
      Sachs, Na, Kreutzer, Mysius)
  8   Solid competition or major UCR (Sorogoyen, Godrèche, Wollner, Schlöndorff)
  7   Strong UCR / established Fortnight (Barnard, Dumont, Alonso, Maurel,
      Kurosawa premiere, Canet, Mandico)
  6   Established parallel-section veteran or notable debut (Firstman, Wigon,
      Sotomayor, Esiri brothers)
  5   Solid programme but niche (Dusabejambo, Shah, Kotzamani debuts)
  4   Modest debut
  3   Minor debut / shorts program (not comp)
  2   Special screening / tribute / restored
"""

FILMS = {
    # ========= COMPETITION =========
    'PAPER TIGER': {
        'director': 'James Gray',
        'section_tag': 'Competition',
        'country': 'USA',
        'runtime': 115,
        'synopsis': 'Two brothers chase the American dream through the Russian mafia in New York. Adam Driver, Scarlett Johansson, Miles Teller. Gray\u2019s first since Armageddon Time.',
        'director_note': 'James Gray \u2014 Two Lovers, The Immigrant, Armageddon Time. Sober American crime auteur.',
        'taste': 9,
        'prestige': 9,
        'tags': ['crime', 'American', 'star-packed'],
    },
    'MOULIN': {
        'director': 'L\u00e1szl\u00f3 Nemes',
        'section_tag': 'Competition',
        'country': 'France/Hungary',
        'runtime': 130,
        'synopsis': 'Biopic of French Resistance leader Jean Moulin (Gilles Lellouche) by the Son of Saul / Sunset director.',
        'director_note': 'L\u00e1szl\u00f3 Nemes \u2014 Son of Saul (Grand Prix 2015, Best Foreign Oscar).',
        'taste': 7,
        'prestige': 9,
        'tags': ['war', 'biopic', 'immersive'],
    },
    'HOPE': {
        'director': 'Na Hong-jin',
        'section_tag': 'Competition',
        'country': 'South Korea',
        'runtime': 160,
        'synopsis': 'Near the DMZ, a police chief (Hwang Jung-min, Jo In-sung) investigates a tiger sighting that spirals into sci-fi catastrophe. Fassbender, Vikander. Biggest-budget Korean film ever. 10 years after The Wailing.',
        'director_note': 'Na Hong-jin \u2014 The Chaser, The Yellow Sea, The Wailing. Genre master of dread.',
        'taste': 10,
        'prestige': 9,
        'tags': ['Korean', 'thriller', 'sci-fi', 'peak match'],
    },
    'SHEEP IN THE BOX': {
        'director': 'Kore-eda Hirokazu',
        'section_tag': 'Competition',
        'country': 'Japan',
        'runtime': 126,
        'synopsis': 'Near-future drama: a grieving couple adopts a humanoid robot modelled on their late son. Haruka Ayase.',
        'director_note': 'Kore-eda \u2014 Palme winner (Shoplifters 2018). Gentle, observant family cinema.',
        'taste': 6,
        'prestige': 10,
        'tags': ['Japanese', 'sci-fi', 'family'],
    },
    'GENTLE MONSTER': {
        'director': 'Marie Kreutzer',
        'section_tag': 'Competition',
        'country': 'Austria',
        'runtime': 114,
        'synopsis': 'Two women (Lucy and Elsa) orbit men whose dark sides they refuse to see. From the Corsage director.',
        'director_note': 'Marie Kreutzer \u2014 Corsage. Measured period-adjacent drama.',
        'taste': 6,
        'prestige': 9,
        'tags': ['female-led', 'psychological'],
    },
    'EL SER QUERIDO': {
        'director': 'Rodrigo Sorogoyen',
        'section_tag': 'Competition',
        'country': 'Spain',
        'runtime': 135,
        'synopsis': 'Javier Bardem as a stoic auteur director trapped on a remote film shoot with his estranged actress daughter. Meta-cinema from The Beasts / Riot Police director.',
        'director_note': 'Rodrigo Sorogoyen \u2014 The Beasts, Riot Police. Tight, tension-heavy Spanish cinema.',
        'taste': 8,
        'prestige': 8,
        'tags': ['Spanish', 'family', 'meta-cinema'],
    },
    'EL SER QUERIDO (THE BELOVED)': {'alias_of': 'EL SER QUERIDO'},
    'SOUDAIN': {
        'director': 'Ryusuke Hamaguchi',
        'section_tag': 'Competition',
        'country': 'France/Japan',
        'runtime': 196,
        'synopsis': 'Hamaguchi\u2019s French debut. Virginie Efira runs a suburban Paris nursing home; her encounter with a terminally ill Japanese playwright (Tao Okamoto) transforms her life. 3h16 min.',
        'director_note': 'Ryusuke Hamaguchi \u2014 Drive My Car (Oscar), Evil Does Not Exist.',
        'taste': 4,
        'prestige': 10,
        'tags': ['French', 'Japanese', 'slow-burn', 'long'],
    },
    'FATHERLAND': {
        'director': 'Pawel Pawlikowski',
        'section_tag': 'Competition',
        'country': 'Germany/Poland',
        'runtime': 130,
        'synopsis': 'Sandra H\u00fcller and Hanns Zischler as Thomas Mann and daughter Erika on a 1949 road trip through ruined postwar Germany.',
        'director_note': 'Pawlikowski \u2014 Ida (Oscar), Cold War. B&W formalist. You rated Cold War 3 stars.',
        'taste': 5,
        'prestige': 9,
        'tags': ['historical', 'road movie', 'German'],
    },
    'GARANCE': {
        'director': 'Jeanne Herry',
        'section_tag': 'Competition',
        'country': 'France',
        'runtime': 120,
        'synopsis': 'Eight years in the life of an alcoholic actress played by Ad\u00e8le Exarchopoulos.',
        'director_note': 'Jeanne Herry \u2014 Pupille, All Your Faces. Humane ensemble drama.',
        'taste': 7,
        'prestige': 8,
        'tags': ['French', 'character study', 'actress showcase'],
    },
    'FJORD': {
        'director': 'Cristian Mungiu',
        'section_tag': 'Competition',
        'country': 'Romania/Norway',
        'runtime': 146,
        'synopsis': 'Romanian-Norwegian couple (Sebastian Stan, Renate Reinsve) settles in a remote fjord village; suspicion mounts that they are harming their children.',
        'director_note': 'Mungiu \u2014 Palme winner (4 Months, 3 Weeks and 2 Days). Cold, ethically-charged slow-burn.',
        'taste': 7,
        'prestige': 10,
        'tags': ['Nordic', 'slow-burn', 'guilt'],
    },
    "L'INCONNUE": {
        'director': 'Arthur Harari',
        'section_tag': 'Competition',
        'country': 'France',
        'runtime': 139,
        'synopsis': 'L\u00e9a Seydoux and Niels Schneider in a body-swap psychological fantasy. A solitary photographer fixates on a mysterious woman, wakes up in her body. Based on Harari brothers\u2019 graphic novel.',
        'director_note': 'Arthur Harari \u2014 Onoda: 10,000 Nights in the Jungle; co-writer of Anatomy of a Fall. Bold, concept-heavy.',
        'taste': 10,
        'prestige': 9,
        'tags': ['surreal', 'body-swap', 'French', 'peak match'],
    },
    "L'INCONNUE (THE UNKNOWN)": {'alias_of': "L'INCONNUE"},
    'HISTOIRES PARALL\u00c8LES': {
        'director': 'Asghar Farhadi',
        'section_tag': 'Competition',
        'country': 'France',
        'runtime': 149,
        'synopsis': 'Huppert, Cassel, Efira, Niney, Deneuve in interconnected narratives around the 2015 Paris attacks, loosely based on Kie\u015blowski\u2019s Dekalog VI. Farhadi\u2019s French debut.',
        'director_note': 'Asghar Farhadi \u2014 A Separation, The Salesman. Two-time Oscar-winning moral storyteller.',
        'taste': 8,
        'prestige': 10,
        'tags': ['French', 'ensemble', 'moral drama'],
    },
    'AMARGA NAVIDAD': {
        'director': 'Pedro Almod\u00f3var',
        'section_tag': 'Competition',
        'country': 'Spain',
        'runtime': 115,
        'synopsis': 'Bitter Christmas. Elsa, an ad pro suffering panic attacks, flees Madrid for an island with her friend Patricia. Almod\u00f3var\u2019s first Spanish feature since The Room Next Door.',
        'director_note': 'Pedro Almod\u00f3var \u2014 Volver, All About My Mother, Pain and Glory. Seventh Palme competition entry.',
        'taste': 9,
        'prestige': 10,
        'tags': ['Spanish', 'melodrama', 'camp'],
    },
    'DIAMOND': {
        'director': 'Andy Garcia',
        'section_tag': 'Out of Competition',
        'country': 'USA',
        'runtime': 120,
        'synopsis': 'Garcia as Joe Diamond, a contemporary L.A. noir protagonist with traumatic past who solves crimes beyond LAPD capacity.',
        'director_note': 'Andy Garcia \u2014 directorial passion project, classic noir sensibilities.',
        'taste': 5,
        'prestige': 4,
        'tags': ['noir', 'American'],
    },
    'COWARD': {
        'director': 'Lukas Dhont',
        'section_tag': 'Competition',
        'country': 'Belgium',
        'runtime': 120,
        'synopsis': '1916 Belgian WWI trenches. Pierre meets flamboyant Francis who stages theatre for fellow soldiers. A queer survival tale.',
        'director_note': 'Lukas Dhont \u2014 Close (Grand Prix 2022), Girl (Camera d\u2019Or 2018). You rated Close 3.5 stars.',
        'taste': 5,
        'prestige': 9,
        'tags': ['war', 'queer', 'Belgian'],
    },
    'THE MAN I LOVE': {
        'director': 'Ira Sachs',
        'section_tag': 'Competition',
        'country': 'USA',
        'runtime': 120,
        'synopsis': 'Musical fantasia set in 1984 NYC. Rami Malek, Tom Sturridge, Rebecca Hall, Ebon Moss-Bachrach. Focused on the AIDS crisis and a group of artists.',
        'director_note': 'Ira Sachs \u2014 Passages, Love Is Strange. Intimate queer character work.',
        'taste': 7,
        'prestige': 9,
        'tags': ['queer', 'New York', 'musical'],
    },
    'MINOTAUR': {
        'director': 'Andrey Zvyagintsev',
        'section_tag': 'Competition',
        'country': 'Russia',
        'runtime': 140,
        'synopsis': 'Russia 2022. Gleb, a successful company director, cracks under corporate and geopolitical pressure; carefully ordered life collapses into violence. First Zvyagintsev feature in a decade.',
        'director_note': 'Zvyagintsev \u2014 Leviathan, Loveless, The Return. Austere, powerful, now exiled.',
        'taste': 7,
        'prestige': 10,
        'tags': ['Russian', 'political thriller'],
    },
    'MINOTAURE': {'alias_of': 'MINOTAUR'},
    'LA BOLA NEGRA': {
        'director': 'Los Javis (Calvo & Ambrossi)',
        'section_tag': 'Competition',
        'country': 'Spain',
        'runtime': 115,
        'synopsis': 'Based on an unfinished play by Federico Garc\u00eda Lorca. Pen\u00e9lope Cruz stars. Los Javis (Veneno, La Mes\u00edas) directorial debut at this scale.',
        'director_note': 'Javier Calvo & Javier Ambrossi \u2014 prolific Spanish TV auteurs (Veneno, La Mes\u00edas).',
        'taste': 8,
        'prestige': 8,
        'tags': ['Spanish', 'Lorca', 'queer', 'stylish'],
    },
    'DAS GETR\u00c4UMTE ABENTEUER': {
        'director': 'Valeska Grisebach',
        'section_tag': 'Competition',
        'country': 'Germany/Bulgaria',
        'runtime': 120,
        'synopsis': 'Bulgarian border town. A woman gets involved in illegal trade to help a man she shares a bond with. Grisebach\u2019s first since Western (2017).',
        'director_note': 'Grisebach \u2014 Western, Longing. Restrained Berlin School realism.',
        'taste': 3,
        'prestige': 8,
        'tags': ['German', 'Balkan', 'slow'],
    },
    'THE DREAMED ADVENTURE': {'alias_of': 'DAS GETR\u00c4UMTE ABENTEUER'},
    'HISTOIRES DE LA NUIT': {
        'director': 'L\u00e9a Mysius',
        'section_tag': 'Competition',
        'country': 'France',
        'runtime': 130,
        'synopsis': 'Rural France. A man plans a surprise birthday for his wife; inexplicable events disturb a quiet hamlet and escalate into a nightmare. Hafsia Herzi, Beno\u00eet Magimel, Monica Bellucci. Based on a Booker-longlisted novel.',
        'director_note': 'L\u00e9a Mysius \u2014 Ava, The Five Devils. Mysterious, sensual, genre-tinted.',
        'taste': 9,
        'prestige': 9,
        'tags': ['French', 'psychological thriller', 'rural horror'],
    },
    'HISTOIRES DE LA NUIT (THE BIRTHDAY PAR': {'alias_of': 'HISTOIRES DE LA NUIT'},
    'NOTRE SALUT': {
        'director': 'Emmanuel Marre',
        'section_tag': 'Competition',
        'country': 'France/Belgium',
        'runtime': 120,
        'synopsis': 'WWII Resistance drama. Swann Arlaud (Anatomy of a Fall) as Henri Marre navigates occupied France.',
        'director_note': 'Marre \u2014 cin\u00e9aste behind Zero Fucks Given (2021 Semaine).',
        'taste': 5,
        'prestige': 8,
        'tags': ['French', 'WWII', 'resistance'],
    },

    # ========= CANNES PREMIERE =========
    'HEIMSUCHUNG (LE BOIS DE KLARA / VISITA': {
        'director': 'Volker Schl\u00f6ndorff',
        'section_tag': 'Cannes Premiere',
        'country': 'Germany',
        'runtime': 118,
        'synopsis': 'A lakeside house near Berlin witnesses a century of German history \u2014 Nazism, war, Soviet occupation, reunification.',
        'director_note': 'Schl\u00f6ndorff \u2014 Palme winner (The Tin Drum, 1979). Veteran German auteur.',
        'taste': 5,
        'prestige': 8,
        'tags': ['German', 'historical', 'epic'],
    },
    'LE BOIS DE KLARA': {'alias_of': 'HEIMSUCHUNG (LE BOIS DE KLARA / VISITA'},
    'LA TROISI\u00c8ME NUIT (WHEN THE NIGHT FAL': {
        'director': 'Daniel Auteuil',
        'section_tag': 'Cannes Premiere',
        'country': 'France',
        'runtime': 100,
        'synopsis': '1942 Lyon. True story of a civil servant (Antoine Reinartz) and a priest (Auteuil) who saved 100+ Jewish children from deportation.',
        'director_note': 'Daniel Auteuil \u2014 acclaimed actor turned director (The Thread).',
        'taste': 4,
        'prestige': 6,
        'tags': ['French', 'WWII', 'drama'],
    },
    'AQU\u00cd': {
        'director': 'Tiago Guedes',
        'section_tag': 'Cannes Premiere',
        'country': 'Portugal',
        'runtime': 203,
        'synopsis': 'Adaptation of J.M. Coetzee\u2019s Jesus Trilogy. Strangers cross the ocean to a new life; past erased, time begins. 3h23 min.',
        'director_note': 'Guedes \u2014 The Domain, Remains of the Wind.',
        'taste': 4,
        'prestige': 6,
        'tags': ['Portuguese', 'literary', 'long'],
    },
    "KOKUROJO (LE CH\u00c2TEAU D'ARIOKA / THE S": {
        'director': 'Kiyoshi Kurosawa',
        'section_tag': 'Cannes Premiere',
        'country': 'Japan',
        'runtime': 130,
        'synopsis': 'The Samurai and the Prisoner. A samurai isolated in a fortress faces a series of mysterious crimes. Adapted from the Naoki Prize-winning Honobu Yonezawa novel.',
        'director_note': 'Kiyoshi Kurosawa \u2014 Pulse, Cure, Tokyo Sonata. Master of atmospheric dread.',
        'taste': 9,
        'prestige': 8,
        'tags': ['Japanese', 'samurai', 'mystery'],
    },
    "LE CH\u00c2TEAU D'ARIOKA": {'alias_of': "KOKUROJO (LE CH\u00c2TEAU D'ARIOKA / THE S"},
    "MARIAGE AU GO\u00dbT D'ORANGE": {
        'director': 'Christophe Honor\u00e9',
        'section_tag': 'Cannes Premiere',
        'country': 'France',
        'runtime': 115,
        'synopsis': '1978 Nantes. A family reunites for a wedding while the father has been banished.',
        'director_note': 'Christophe Honor\u00e9 \u2014 Love Songs, Sorry Angel. French queer family cinema.',
        'taste': 6,
        'prestige': 7,
        'tags': ['French', 'family'],
    },
    'THE END OF IT': {
        'director': 'Mar\u00eda Mart\u00ednez Bayona',
        'section_tag': 'Cannes Premiere',
        'country': 'Spain',
        'runtime': 100,
        'synopsis': 'Spanish debut feature, late Cannes Premiere addition.',
        'director_note': 'Debut feature.',
        'taste': 5,
        'prestige': 6,
        'tags': ['Spanish', 'debut'],
    },

    # ========= OUT OF COMPETITION / MIDNIGHT =========
    'KARMA': {
        'director': 'Guillaume Canet',
        'section_tag': 'Out of Competition',
        'country': 'France',
        'runtime': 149,
        'synopsis': 'Psychological thriller. Marion Cotillard, Denis M\u00e9nochet.',
        'director_note': 'Guillaume Canet \u2014 Tell No One, Little White Lies.',
        'taste': 7,
        'prestige': 6,
        'tags': ['French', 'thriller'],
    },
    "LA BATAILLE DE GAULLE : L'\u00c2GE DE FER": {
        'director': 'Antonin Baudry',
        'section_tag': 'Out of Competition',
        'country': 'France',
        'runtime': 140,
        'synopsis': 'Part 1 of a De Gaulle biopic diptych. June 1940: France falls; De Gaulle escapes to London. Simon Abkarian as De Gaulle.',
        'director_note': 'Baudry \u2014 The Wolf\u2019s Call (2019).',
        'taste': 4,
        'prestige': 5,
        'tags': ['French', 'WWII', 'biopic'],
    },
    'HER PRIVATE HELL': {
        'director': 'Nicolas Winding Refn',
        'section_tag': 'Out of Competition',
        'country': 'USA/Denmark',
        'runtime': 109,
        'synopsis': 'Futuristic metropolis engulfed in mist, a deadly entity, a troubled woman searching for her father, colliding with an American GI on a quest to rescue his daughter from Hell. Sophie Thatcher, Charles Melton, Dougray Scott, Diego Calva. Refn\u2019s first since The Neon Demon (2016).',
        'director_note': 'Nicolas Winding Refn \u2014 Drive, Only God Forgives, The Neon Demon. Neon-drenched style auteur.',
        'taste': 10,
        'prestige': 8,
        'tags': ['stylised', 'genre', 'horror', 'peak match'],
    },
    'FULL PHIL': {
        'director': 'Quentin Dupieux',
        'section_tag': 'Midnight Screenings',
        'country': 'France/USA',
        'runtime': 78,
        'synopsis': 'American billionaire tries to reconnect with his daughter in Paris; a 1950s horror film and an invasive hotel employee derail them. Woody Harrelson, Kristen Stewart, Emma Mackey, Charlotte Le Bon, Tim Heidecker.',
        'director_note': 'Quentin Dupieux \u2014 Rubber, Deerskin, Smoking Causes Coughing. Prolific absurdist.',
        'taste': 9,
        'prestige': 7,
        'tags': ['absurdist', 'comedy', 'English'],
    },
    'GUN-CHE': {
        'director': 'Yeon Sang-ho',
        'section_tag': 'Midnight Screenings',
        'country': 'South Korea',
        'runtime': 110,
        'synopsis': 'Colony. A biotech conference becomes ground zero for a mutating virus; the building is locked down with zombies evolving and observing. Gianna Jun.',
        'director_note': 'Yeon Sang-ho \u2014 Train to Busan, Peninsula. Genre showman.',
        'taste': 9,
        'prestige': 7,
        'tags': ['Korean', 'zombie', 'midnight'],
    },
    'JIM QUEEN': {
        'director': 'Marco Nguyen & Nicolas Athan\u00e9',
        'section_tag': 'Midnight Screenings',
        'country': 'France',
        'runtime': 85,
        'synopsis': 'Animated queer satire. A gay influencer\u2019s life crumbles when a virus turns Paris\u2019s gay men straight; he teams with a twink to find a rumored cure in the Marais. BobbyPills banner (Captain Laserhawk).',
        'director_note': 'Debut feature from BobbyPills animators.',
        'taste': 7,
        'prestige': 5,
        'tags': ['animation', 'queer', 'satire'],
    },
    'ROMA ELASTICA': {
        'director': 'Bertrand Mandico',
        'section_tag': 'Midnight Screenings',
        'country': 'France/Italy',
        'runtime': 95,
        'synopsis': 'Marion Cotillard as a washed-up movie star with her loyal makeup artist (No\u00e9mie Merlant) on a sci-fi shoot in Rome. Homage to 1980s Cinecitt\u00e0.',
        'director_note': 'Bertrand Mandico \u2014 The Wild Boys, Conann. Dreamlike, tactile, experimental.',
        'taste': 10,
        'prestige': 7,
        'tags': ['French', 'experimental', 'queer', 'peak match'],
    },
    "L'OBJET DU D\u00c9LIT": {
        'director': 'Agn\u00e8s Jaoui',
        'section_tag': 'Out of Competition',
        'country': 'France',
        'runtime': 100,
        'synopsis': 'Crescendo. A French comedy.',
        'director_note': 'Agn\u00e8s Jaoui \u2014 Le Go\u00fbt des Autres (Oscar-nominated).',
        'taste': 5,
        'prestige': 5,
        'tags': ['French', 'comedy'],
    },

    # ========= UN CERTAIN REGARD =========
    'SIEMPRE SOY TU ANIMAL MATERNO (TON A': {
        'director': 'Valentina Maurel',
        'section_tag': 'UCR',
        'country': 'Costa Rica',
        'runtime': 100,
        'synopsis': 'Forever Your Maternal Animal. Elsa returns to Costa Rica after Europe and reconnects with her mentally fragile sister; parents retreat into themselves.',
        'director_note': 'Maurel \u2014 Tengo sue\u00f1os el\u00e9ctricos (Locarno 2022 Best Director).',
        'taste': 6,
        'prestige': 7,
        'tags': ['Latin American', 'family'],
    },
    'TON ANIMAL MATERNEL (SIEMPRE SOY TU': {'alias_of': 'SIEMPRE SOY TU ANIMAL MATERNO (TON A'},
    'MEMOIRE DE FILLE': {
        'director': 'Judith Godr\u00e8che',
        'section_tag': 'UCR',
        'country': 'France',
        'runtime': 117,
        'synopsis': 'A Girl\u2019s Story. Adapts Annie Ernaux; Godr\u00e8che plays the writer returning to Rouen, sent reeling back to her first sexual night. Powerful French #MeToo voice.',
        'director_note': 'Judith Godr\u00e8che \u2014 major actress, breakout as director with Moi Aussi (2024).',
        'taste': 7,
        'prestige': 8,
        'tags': ['French', 'MeToo', 'literary'],
    },
    'ALL THE LOVERS IN THE NIGHT (DE TOUTES': {
        'director': 'Yukiko Sode',
        'section_tag': 'UCR',
        'country': 'Japan',
        'runtime': 139,
        'synopsis': 'Adaptation of Mieko Kawakami novel. Fuyuko, a solitary freelance proofreader, is transformed after meeting a quiet high school physics teacher (Tadanobu Asano).',
        'director_note': 'Yukiko Sode \u2014 Aristocrats (2020).',
        'taste': 6,
        'prestige': 7,
        'tags': ['Japanese', 'literary', 'quiet'],
    },
    'DE TOUTES LES NUITS, LES AMANTS (SUBE': {'alias_of': 'ALL THE LOVERS IN THE NIGHT (DE TOUTES'},
    "I'LL BE GONE IN JUNE": {
        'director': 'Katharina Rivilis',
        'section_tag': 'UCR',
        'country': 'Germany/USA',
        'runtime': 125,
        'synopsis': '2001 New Mexico desert. A German exchange student navigates school days and finds queer tenderness with a sad boy as 9/11 echoes.',
        'director_note': 'Directorial debut.',
        'taste': 4,
        'prestige': 5,
        'tags': ['coming-of-age', 'queer', 'debut'],
    },
    'EVERYTIME': {
        'director': 'Sandra Wollner',
        'section_tag': 'UCR',
        'country': 'Austria',
        'runtime': 121,
        'synopsis': 'A tragedy brings a mother, daughter, and the teenage boy blamed for it on a Tenerife holiday that never happened; past and present overlap. Birgit Minichmayr.',
        'director_note': 'Sandra Wollner \u2014 The Trouble With Being Born. Chilly, precise, haunting.',
        'taste': 8,
        'prestige': 7,
        'tags': ['Austrian', 'psychological', 'grief'],
    },
    'CONGO BOY': {
        'director': 'Rafiki Fariala',
        'section_tag': 'UCR',
        'country': 'DR Congo',
        'runtime': 126,
        'synopsis': '17-year-old Robert dreams of a music career while civil war tears the country apart and he becomes guardian to his siblings after his parents are imprisoned.',
        'director_note': 'Fariala \u2014 Nous, \u00e9tudiants! (2022).',
        'taste': 5,
        'prestige': 6,
        'tags': ['African', 'coming-of-age', 'music'],
    },
    'CLUB KID': {
        'director': 'Jordan Firstman',
        'section_tag': 'UCR',
        'country': 'USA',
        'runtime': 126,
        'synopsis': 'Washed-up NYC party promoter forced to turn his life around when an unexpected visitor arrives. Cara Delevingne, Diego Calva.',
        'director_note': 'Jordan Firstman \u2014 internet-comedy-turned-filmmaker, feature debut.',
        'taste': 8,
        'prestige': 6,
        'tags': ['queer', 'New York', 'debut'],
    },
    'LA M\u00c1S DULCE': {
        'director': 'La\u00efla Marrakchi',
        'section_tag': 'UCR',
        'country': 'Morocco/Spain',
        'runtime': 101,
        'synopsis': 'Moroccan women go to Andalusia to pick strawberries and face abuse and exploitation.',
        'director_note': 'La\u00efla Marrakchi \u2014 Marock (2005).',
        'taste': 5,
        'prestige': 6,
        'tags': ['social realism', 'Morocco', 'Spain'],
    },
    'LA M\u00c1S DULCE (STRAWBERRIES)': {'alias_of': 'LA M\u00c1S DULCE'},
    'LE CORSET': {
        'director': 'Louis Clichy',
        'section_tag': 'UCR',
        'country': 'France',
        'runtime': 103,
        'synopsis': 'Iron Boy. Animated. Rural France, 10-year-old Christophe must wear an iron brace; he discovers music and love.',
        'director_note': 'Louis Clichy \u2014 WALL\u00b7E animator, Asterix: Mansion of the Gods.',
        'taste': 6,
        'prestige': 6,
        'tags': ['animation', 'French', 'coming-of-age'],
    },
    'LE CORSET (IRON BOY)': {'alias_of': 'LE CORSET'},
    "BEN'IMANA": {
        'director': 'Marie-Cl\u00e9mentine Dusabejambo',
        'section_tag': 'UCR',
        'country': 'Rwanda',
        'runtime': 108,
        'synopsis': 'Rwanda 2012. Community-led reconciliation trials after the Tutsi genocide. First Rwandan-directed feature at Cannes.',
        'director_note': 'Dusabejambo \u2014 acclaimed Rwandan short filmmaker, feature debut.',
        'taste': 4,
        'prestige': 6,
        'tags': ['African', 'debut', 'historical'],
    },
    'ULYA': {
        'director': 'Viesturs Kairi\u0161s',
        'section_tag': 'UCR',
        'country': 'Latvia',
        'runtime': 118,
        'synopsis': 'Latvia 1964. Ulya, an Old Believer teenage girl nearly two meters tall, is drawn into basketball and Soviet-era identity struggle. B&W.',
        'director_note': 'Kairi\u0161s \u2014 January (Tribeca Best Film 2022).',
        'taste': 5,
        'prestige': 6,
        'tags': ['Baltic', 'period', 'sports', 'B&W'],
    },
    'U\u013cA': {'alias_of': 'ULYA'},
    'ELEPHANTS IN THE FOG (LES ELEPHANTS D': {
        'director': 'Abinash Bikram Shah',
        'section_tag': 'UCR',
        'country': 'Nepal',
        'runtime': 110,
        'synopsis': 'A village matriarch of a Kinnar community dreams of escaping to live with the man she loves. First-ever Nepali film at Cannes.',
        'director_note': 'Bikram Shah \u2014 co-writer of Shambhala; feature debut.',
        'taste': 5,
        'prestige': 5,
        'tags': ['Nepali', 'debut', 'quiet'],
    },
    'LES ELEPHANTS DANS LA BRUME (ELEPHA': {'alias_of': 'ELEPHANTS IN THE FOG (LES ELEPHANTS D'},
    "YESTERDAY THE EYE DIDN'T SLEEP": {
        'director': 'Rakan Mayasi',
        'section_tag': 'UCR',
        'country': 'Lebanon/Palestine',
        'runtime': 115,
        'synopsis': 'Bekaa Valley, Lebanon/Syria border. A burnt truck sparks a cycle of vengeance in a Bedouin community.',
        'director_note': 'Rakan Mayasi \u2014 Palestinian short filmmaker, feature debut.',
        'taste': 5,
        'prestige': 6,
        'tags': ['Arab', 'debut', 'tribal'],
    },
    'UNE DISPARITION (YESTERDAY THE EYE DI': {'alias_of': "YESTERDAY THE EYE DIDN'T SLEEP"},
    'VICTORIAN PSYCHO': {
        'director': 'Zachary Wigon',
        'section_tag': 'UCR',
        'country': 'USA/UK',
        'runtime': 110,
        'synopsis': 'Gothic psychological thriller. A governess with hidden psychopathic tendencies arrives at Ensor House; staff start disappearing. Maika Monroe, Thomasin McKenzie, Jason Isaacs, Ruth Wilson, Jacobi Jupe.',
        'director_note': 'Zachary Wigon \u2014 Sanctuary (2022).',
        'taste': 10,
        'prestige': 6,
        'tags': ['gothic', 'horror', 'English'],
    },
    'TITANIC OCEAN': {
        'director': 'Konstantina Kotzamani',
        'section_tag': 'UCR',
        'country': 'Greece/Japan',
        'runtime': 105,
        'synopsis': 'Japanese boarding school trains teenage girls into professional mermaids; 17-year-old Akame finds her siren voice, first love, metamorphosis.',
        'director_note': 'Kotzamani \u2014 celebrated Greek short filmmaker, feature debut.',
        'taste': 8,
        'prestige': 6,
        'tags': ['Greek', 'Japanese', 'surreal', 'debut'],
    },
    'ULYSSE': {
        'director': 'Laetitia Masson',
        'section_tag': 'UCR',
        'country': 'France',
        'runtime': 100,
        'synopsis': 'Closing film of Un Certain Regard.',
        'director_note': 'Laetitia Masson \u2014 French filmmaker (En avoir (ou pas)).',
        'taste': 4,
        'prestige': 5,
        'tags': ['French'],
    },
    'CL\u00d4TURE UN CERTAIN REGARD - ULYSSE': {'alias_of': 'ULYSSE'},

    # ========= DIRECTORS' FORTNIGHT =========
    'DORA': {
        'director': 'July Jung',
        'section_tag': 'DF',
        'country': 'South Korea',
        'runtime': 137,
        'synopsis': 'Summer seaside village in South Korea. A young woman struggles physically and mentally; begins to recover through love. Sakura Ando, Kim Doyeon.',
        'director_note': 'July Jung \u2014 A Girl at My Door, Next Sohee.',
        'taste': 6,
        'prestige': 7,
        'tags': ['Korean', 'female-led'],
    },
    'SHANA': {
        'director': 'Lila Pinell',
        'section_tag': 'DF',
        'country': 'France',
        'runtime': 83,
        'synopsis': 'French Fortnight debut.',
        'director_note': 'Lila Pinell \u2014 co-director of Kiss & Cry.',
        'taste': 5,
        'prestige': 5,
        'tags': ['French', 'debut'],
    },
    'CLARISSA': {
        'director': 'Chuko & Arie Esiri',
        'section_tag': 'DF',
        'country': 'Nigeria',
        'runtime': 123,
        'synopsis': 'Nigerian DF entry. From Eyimofe directors.',
        'director_note': 'Esiri brothers \u2014 Eyimofe (This Is My Desire).',
        'taste': 6,
        'prestige': 7,
        'tags': ['African', 'Nigerian'],
    },
    "L'ESP\u00c8CE EXPLOSIVE": {
        'director': 'Sarah Arnold',
        'section_tag': 'DF',
        'country': 'France',
        'runtime': 95,
        'synopsis': 'Too Many Beasts. A volatile police officer newly transferred investigates a year-old case while wild boars multiply; pushed to the brink.',
        'director_note': 'Sarah Arnold \u2014 French feature debut.',
        'taste': 7,
        'prestige': 5,
        'tags': ['French', 'thriller', 'debut'],
    },
    'L\u2019ESP\u00c8CE EXPLOSIVE': {'alias_of': "L'ESP\u00c8CE EXPLOSIVE"},
    'DOUBLE FREEDOM': {
        'director': 'Lisandro Alonso',
        'section_tag': 'DF',
        'country': 'Argentina',
        'runtime': 98,
        'synopsis': 'La libertad doble. Sequel to Alonso\u2019s 2001 debut. Woodcutter Misael, 25 years later; unbidden responsibility upends solitary freedom.',
        'director_note': 'Lisandro Alonso \u2014 Jauja, Eureka. Slow, meditative master.',
        'taste': 3,
        'prestige': 7,
        'tags': ['Argentine', 'slow', 'meditative'],
    },
    'LA PERRA': {
        'director': 'Dominga Sotomayor',
        'section_tag': 'DF',
        'country': 'Chile',
        'runtime': 110,
        'synopsis': 'From the Too Late to Die Young director.',
        'director_note': 'Sotomayor \u2014 Locarno Golden Leopard winner (2018).',
        'taste': 5,
        'prestige': 6,
        'tags': ['Chilean'],
    },
    'BUTTERFLY JAM': {
        'director': 'Kantemir Balagov',
        'section_tag': 'DF',
        'country': 'USA/Russia',
        'runtime': 120,
        'synopsis': 'Fortnight opening film. English-language debut set in a tight-knit US community. Barry Keoghan, Riley Keough.',
        'director_note': 'Balagov \u2014 Beanpole, Closeness. Intense, gut-punching.',
        'taste': 8,
        'prestige': 7,
        'tags': ['American', 'intense', 'Russian auteur'],
    },
    'ONCE UPON A TIME IN HARLEM': {
        'director': 'David & William Greaves',
        'section_tag': 'DF',
        'country': 'USA',
        'runtime': 104,
        'synopsis': 'Doc on the Harlem Renaissance. Premiered at Sundance.',
        'director_note': 'David Greaves completing his late father William Greaves\u2019 work.',
        'taste': 4,
        'prestige': 5,
        'tags': ['documentary', 'history'],
    },
    'I SEE BUILDINGS FALL LIKE LIGHTNING': {
        'director': 'Clio Barnard',
        'section_tag': 'DF',
        'country': 'UK',
        'runtime': 115,
        'synopsis': 'Ensemble drama of old friendships and new crises. Anthony Boyle, Joe Cole, Jay Lycurgo, Daryl McCormack, Lola Petticrew.',
        'director_note': 'Clio Barnard \u2014 The Selfish Giant, Ali & Ava.',
        'taste': 6,
        'prestige': 7,
        'tags': ['British', 'ensemble'],
    },
    'LES ROCHES ROUGES': {
        'director': 'Bruno Dumont',
        'section_tag': 'DF',
        'country': 'France',
        'runtime': 95,
        'synopsis': 'Red Rocks. Kids cliff-jumping on the French Riviera; G\u00e9o discovers friendship, rivalry and first love.',
        'director_note': 'Bruno Dumont \u2014 Hadewijch, L\u2019Humanit\u00e9. Singular French provocateur.',
        'taste': 5,
        'prestige': 7,
        'tags': ['French', 'coming-of-age'],
    },
    'LES ROCHES ROUGES + MASTERCLASS BRU': {'alias_of': 'LES ROCHES ROUGES'},
    'LE VERTIGE': {
        'director': 'Quentin Dupieux',
        'section_tag': 'DF',
        'country': 'France',
        'runtime': 75,
        'synopsis': 'Vertiginous. Animated feature. Dupieux\u2019s second Cannes 2026 film.',
        'director_note': 'Quentin Dupieux \u2014 also Full Phil this year.',
        'taste': 8,
        'prestige': 6,
        'tags': ['animation', 'absurdist'],
    },
    'LE VERTIGE (VERTIGINOUS)': {'alias_of': 'LE VERTIGE'},
    'DEATH HAS NO MASTER (LA MUERTE NO TI': {
        'director': 'Jorge Thielen Armand',
        'section_tag': 'DF',
        'country': 'Venezuela',
        'runtime': 110,
        'synopsis': 'Asia Argento as a Venezuelan heiress returning home to reclaim her father\u2019s cacao plantation; violence ensues.',
        'director_note': 'Thielen Armand \u2014 La Soledad, La Fortaleza.',
        'taste': 7,
        'prestige': 6,
        'tags': ['Latin American', 'thriller'],
    },
    "CARMEN, L'OISEAU REBELLE": {
        'director': 'S\u00e9bastien Laudenbach',
        'section_tag': 'DF',
        'country': 'France',
        'runtime': 80,
        'synopsis': 'Animated Viva Carmen. Reinterpretation of Bizet\u2019s Carmen.',
        'director_note': 'Laudenbach \u2014 The Girl Without Hands.',
        'taste': 6,
        'prestige': 6,
        'tags': ['animation', 'French'],
    },
    'CARMEN, L\u2019OISEAU REBELLE': {'alias_of': "CARMEN, L'OISEAU REBELLE"},
    'ATONEMENT': {
        'director': 'Reed Van Dyk',
        'section_tag': 'DF',
        'country': 'USA',
        'runtime': 100,
        'synopsis': 'L\u2019Apaisement. Fortnight entry.',
        'director_note': 'Reed Van Dyk \u2014 debut feature filmmaker.',
        'taste': 5,
        'prestige': 5,
        'tags': ['American', 'debut'],
    },
    'GABIN': {
        'director': 'Maxence Voiseux',
        'section_tag': 'DF',
        'country': 'France',
        'runtime': 95,
        'synopsis': 'French DF entry.',
        'director_note': 'Debut feature.',
        'taste': 4,
        'prestige': 5,
        'tags': ['French', 'debut'],
    },
    'WE ARE ALIENS': {
        'director': 'Kohei Kadowaki',
        'section_tag': 'DF',
        'country': 'Japan',
        'runtime': 95,
        'synopsis': 'Japanese animated Fortnight entry.',
        'director_note': 'Kadowaki \u2014 Japanese animator.',
        'taste': 6,
        'prestige': 5,
        'tags': ['animation', 'Japanese'],
    },
    "MERCI D'\u00caTRE VENU": {
        'director': 'Alain Cavalier',
        'section_tag': 'DF',
        'country': 'France',
        'runtime': 85,
        'synopsis': 'Latest from French veteran Alain Cavalier.',
        'director_note': 'Alain Cavalier \u2014 Th\u00e9r\u00e8se, Le Combat dans l\u2019\u00eele.',
        'taste': 4,
        'prestige': 6,
        'tags': ['French', 'veteran'],
    },
    '9 TEMPLES TO HEAVEN': {
        'director': 'Sompot Chidgasorpongse',
        'section_tag': 'DF',
        'country': 'Thailand',
        'runtime': 110,
        'synopsis': 'Thai Fortnight entry.',
        'director_note': 'Thai filmmaker.',
        'taste': 5,
        'prestige': 5,
        'tags': ['Thai'],
    },
    'LOW EXPECTATIONS': {
        'director': 'Eivind Landsvik',
        'section_tag': 'DF',
        'country': 'Norway',
        'runtime': 100,
        'synopsis': 'Norwegian Fortnight entry.',
        'director_note': 'Debut feature.',
        'taste': 5,
        'prestige': 5,
        'tags': ['Norwegian', 'debut'],
    },

    # ========= SEMAINE DE LA CRITIQUE =========
    'LA GRADIVA': {
        'director': 'Marine Atlan',
        'section_tag': 'Semaine',
        'country': 'France',
        'runtime': 85,
        'synopsis': 'French Critics\u2019 Week entry.',
        'director_note': 'Marine Atlan \u2014 French filmmaker.',
        'taste': 5,
        'prestige': 5,
        'tags': ['French', 'debut'],
    },
    'LA FRAPPE': {
        'director': 'Julien Gaspar-Oliveri',
        'section_tag': 'Semaine',
        'country': 'France',
        'runtime': 110,
        'synopsis': 'French Critics\u2019 Week entry.',
        'director_note': 'French debut filmmaker.',
        'taste': 5,
        'prestige': 5,
        'tags': ['French', 'debut'],
    },
    'THE STATION': {
        'director': 'Sara Ishaq',
        'section_tag': 'Semaine',
        'country': 'Yemen/UK',
        'runtime': 110,
        'synopsis': 'Al Mahattah. Yemeni debut feature.',
        'director_note': 'Sara Ishaq \u2014 Oscar-nominated doc filmmaker (Karama Has No Walls).',
        'taste': 5,
        'prestige': 5,
        'tags': ['Arab', 'debut'],
    },
    'THE STATION / AL MAHATTAH': {'alias_of': 'THE STATION'},
    'TIN CASTLE': {
        'director': 'Alexander Murphy',
        'section_tag': 'Semaine',
        'country': 'UK',
        'runtime': 100,
        'synopsis': 'British Critics\u2019 Week entry.',
        'director_note': 'Debut feature.',
        'taste': 5,
        'prestige': 5,
        'tags': ['British', 'debut'],
    },
    'DU FIOUL DANS LES ART\u00c8RES': {
        'director': 'Pierre Le Gall',
        'section_tag': 'Semaine',
        'country': 'France',
        'runtime': 95,
        'synopsis': 'French Critics\u2019 Week entry.',
        'director_note': 'Debut feature.',
        'taste': 4,
        'prestige': 5,
        'tags': ['French', 'debut'],
    },
    'IN WAVES': {
        'director': 'Phuong Mai Nguyen',
        'section_tag': 'Semaine',
        'country': 'France',
        'runtime': 90,
        'synopsis': 'Animated Critics\u2019 Week opening film. Adapts AJ Dungo\u2019s graphic novel about a skater and surfer couple tested by illness in California. Voices: Will Sharpe, Stephanie Hsu.',
        'director_note': 'Phuong Mai Nguyen \u2014 animation debut feature.',
        'taste': 7,
        'prestige': 6,
        'tags': ['animation', 'California', 'romance'],
    },
    'ADIEU MONDE CRUEL': {
        'director': 'Felix De Givry',
        'section_tag': 'Semaine',
        'country': 'France',
        'runtime': 100,
        'synopsis': 'Closing Critics\u2019 Week film.',
        'director_note': 'Debut feature.',
        'taste': 5,
        'prestige': 5,
        'tags': ['French', 'debut'],
    },
    'SEIS MESES EN EL EDIFICIO ROSA CON AZUL': {
        'director': 'Bruno Santamar\u00eda Razo',
        'section_tag': 'Semaine',
        'country': 'Mexico',
        'runtime': 95,
        'synopsis': 'Mexican Critics\u2019 Week entry.',
        'director_note': 'Santamar\u00eda \u2014 Things We Dare Not Do.',
        'taste': 4,
        'prestige': 5,
        'tags': ['Mexican'],
    },

    # ========= OFFICIAL SHORTS / CINEF =========
    'COURTS M\u00c9TRAGES COMP\u00c9TITION 01': {
        'director': 'Various',
        'section_tag': 'Shorts Competition',
        'country': 'International',
        'runtime': 94,
        'synopsis': 'Programme 01 of the Official Short Films Competition. 10 shorts selected from 3,184 entries, 136 countries. Jury chaired by Carla Sim\u00f3n.',
        'director_note': 'Official short films competition.',
        'taste': 7,
        'prestige': 7,
        'tags': ['shorts', 'competition'],
    },
    'COURTS M\u00c9TRAGES COMP\u00c9TITION 02': {
        'director': 'Various',
        'section_tag': 'Shorts Competition',
        'country': 'International',
        'runtime': 100,
        'synopsis': 'Programme 02 of the Official Short Films Competition.',
        'director_note': 'Official short films competition.',
        'taste': 7,
        'prestige': 7,
        'tags': ['shorts', 'competition'],
    },
    'COURTS M\u00c9TRAGES EN COMP\u00c9TITION': {
        'director': 'Various',
        'section_tag': 'Shorts Competition',
        'country': 'International',
        'runtime': 100,
        'synopsis': 'Rerun of the Official Short Films Competition programs.',
        'director_note': 'Official short films competition (rerun).',
        'taste': 7,
        'prestige': 7,
        'tags': ['shorts', 'competition', 'rerun'],
    },

    # ========= SPECIAL SCREENINGS =========
    'AVEDON': {
        'director': 'Ron Howard',
        'section_tag': 'Special',
        'country': 'USA',
        'runtime': 104,
        'synopsis': 'Documentary on photographer Richard Avedon.',
        'director_note': 'Ron Howard \u2014 Apollo 13, A Beautiful Mind.',
        'taste': 6,
        'prestige': 4,
        'tags': ['documentary', 'photography'],
    },
    "L'AFFAIRE MARIE-CLAIRE": {
        'director': 'Lauriane Escaffre & Yvo Muller',
        'section_tag': 'Special',
        'country': 'France',
        'runtime': 102,
        'synopsis': 'Women on Trial. Charlotte Gainsbourg as Gis\u00e8le Halimi defending 16-year-old Marie-Claire Chevalier in the landmark 1972 Bobigny abortion trial.',
        'director_note': 'Escaffre & Muller \u2014 Maria into Life.',
        'taste': 6,
        'prestige': 5,
        'tags': ['French', 'legal drama'],
    },
    'REHEARSALS FOR A REVOLUTION': {
        'director': 'Pegah Ahangarani',
        'section_tag': 'Special',
        'country': 'Iran',
        'runtime': 95,
        'synopsis': 'Iranian special screening doc.',
        'director_note': 'Pegah Ahangarani \u2014 Iranian filmmaker.',
        'taste': 5,
        'prestige': 5,
        'tags': ['Iranian', 'documentary'],
    },
    'LES MATINS MERVEILLEUX': {
        'director': 'Avril Besson',
        'section_tag': 'Special',
        'country': 'France',
        'runtime': 87,
        'synopsis': 'French special screening.',
        'director_note': 'Avril Besson \u2014 debut filmmaker.',
        'taste': 4,
        'prestige': 4,
        'tags': ['French', 'debut'],
    },
    'LUCY LOST': {
        'director': 'Olivier Clert',
        'section_tag': 'Special',
        'country': 'France',
        'runtime': 100,
        'synopsis': 'French special screening.',
        'director_note': '-',
        'taste': 4,
        'prestige': 4,
        'tags': ['French'],
    },
    'VESNA': {
        'director': 'Rostislav Kirpicenko',
        'section_tag': 'Special',
        'country': 'Lithuania',
        'runtime': 93,
        'synopsis': 'Young priest in Russian-occupied SE Ukraine returns bodies of executed civilians to their families.',
        'director_note': 'Lithuanian filmmaker.',
        'taste': 5,
        'prestige': 5,
        'tags': ['Baltic', 'war'],
    },
    'LES SURVIVANTS DU CHE (CHE GUEVARA: T': {
        'director': 'Christophe Dimitri R\u00e9veille',
        'section_tag': 'Special',
        'country': 'France',
        'runtime': 90,
        'synopsis': 'Doc on Che Guevara.',
        'director_note': 'Documentary.',
        'taste': 4,
        'prestige': 4,
        'tags': ['documentary', 'history'],
    },
    "LE TRIANGLE D'OR": {
        'director': 'H\u00e9l\u00e8ne Rosselet-Ruiz',
        'section_tag': 'Special',
        'country': 'France',
        'runtime': 90,
        'synopsis': 'French special screening.',
        'director_note': '-',
        'taste': 4,
        'prestige': 4,
        'tags': ['French'],
    },
}

DEFAULT_META = {
    'director': '',
    'section_tag': 'Other',
    'country': '',
    'runtime': None,
    'synopsis': '',
    'director_note': '',
    'taste': 3,
    'prestige': 3,
    'tags': [],
}
